# from https://www.drupal.org/requirements/php#drupalversions
FROM pmguser/drupal-php7.0-apache:latest
ARG DEBIAN_FRONTEND=noninteractive

ENV XDEBUGINI_PATH=/usr/local/etc/php/conf.d/xdebug.ini

COPY config/php/xdebug.ini /tmp/xdebug.ini

RUN pecl install xdebug \
  && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > $XDEBUGINI_PATH \
  && cat /tmp/xdebug.ini >> $XDEBUGINI_PATH \
  # Install PHPUnit
  && curl -sSL https://phar.phpunit.de/phpunit.phar -o phpunit.phar \
  && chmod +x phpunit.phar \
  && mv phpunit.phar /usr/local/bin/phpunit \
  # sSMTP: note php is configured to use ssmtp, which is configured to send to
  # pximail:1025, which is standard configuration for a mailhog/mailhog image
  # with hostname mail.
  && apt-get update \
  && apt-get install ssmtp --fix-missing -y

COPY ./config/ssmtp/ssmtp.conf /etc/ssmtp/ssmtp.conf

RUN apt-get autoremove -y
