#!/bin/bash

HOST=$(hostname)
line=$(head -n 1 /etc/hosts | awk '{printf "%s %s.localdomain %s ", $1, $2, $2}')
sed -e "1 s/^.*$/${line} ${HOST}/g" /etc/hosts > hosts
cp hosts /etc/hosts
rm hosts

yes Y | sendmailconfig
